# Generated by Django 4.0.4 on 2022-04-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True##model.py에 있는거 하고나서 커멘드에서 python manange.py makemigrations / python manage.py migrate로 실행한다

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
